# Generated by Django 4.1.4 on 2023-02-13 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transacao", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=19)),
                ("saldo", models.FloatField()),
                ("cpf", models.IntegerField()),
                ("dono_da_loja", models.CharField(max_length=19)),
                (
                    "transacoes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transacao.transacao",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
