version: "3.9"

services:
  cnba_db:
    container_name: cnba_db
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_HOST=cnba_db
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 5

  migrations:
    build: .
    command: python manage.py migrate
    environment:
      - POSTGRES_HOST=cnba_db
    depends_on:
      cnba_db:
        condition: service_healthy

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    environment:
      - POSTGRES_HOST=cnba_db
    ports:
      - 8000:8000
    depends_on:
      cnba_db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
