# Generated by Django 4.1.4 on 2023-02-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transacao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transacao",
            name="cartao",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="data",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="hora",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="transacao",
            name="tipo",
            field=models.CharField(max_length=15),
        ),
    ]
