# Generated by Django 4.1.4 on 2023-02-13 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0004_remove_loja_transacoes_alter_loja_id"),
        ("transacao", "0005_alter_transacao_loja"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transacao",
            name="loja",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="loja.loja",
            ),
        ),
    ]
